/*jshint globalstrict:true, sub:true*/
/*global Z*/
'use strict';


Z.DEBUG = true;
Z.MIN_DRAG_DISTANCE = 40;
Z.PATH_PLOT_STEP = 40;

Z.FERRY_UPDATE_INTERVAL = 30;
Z.FERRY_FLOAT_SPEED = 0.2;
Z.FERRY_MAX_SPEED = 3;
Z.FERRY_AGILITY = 20;
Z.FERRY_VELOCITY = 30;
Z.FERRY_ACCELERATION = 0.02;
Z.FERRY_DECELERATION = 0.015;

Z.SWEETSPOT_TOLERANCE = 30;
